ALTER TABLE sessions ADD COLUMN IF NOT EXISTS child_price DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS concession_price DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS vip_price DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS seat_id UUID REFERENCES seats(id) ON DELETE SET NULL;
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'lcoin';
ALTER TABLE registrations ADD COLUMN IF NOT EXISTS paid_amount DECIMAL(10,2) DEFAULT 0;
